site_name: CUAHSI Data Collection Protocols
repo_name: data-collection-protocols
repo_url: https://github.com/CUAHSI/data-collection-protocols
edit_uri_template: 'https://github.com/CUAHSI/data-collection-protocols'

theme:
  name: "material"
  features:
    - search.suggest
    - search.highlight
    - content.action.edit
    - navigation.footer
    - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: default
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to light mode

plugins:
  - search
  - git-revision-date-localized:
      locale: en
      type: datetime

markdown_extensions:
  - tables

nav:
  - Home: index.md
  - "Data collection protocols":
    - "AIMS Project": 
      - "Surface Water Chemistry Field Sampling": AIMS_project/Surface_water_chemistry_sampling.md